= Lab: Counter Component in Plain JavaScript

== Render Custom Element

Create an HTML file with a basic skeleton and open it in your browser:

.counter.html
[source,html]
----
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Counter</title>
</head>
<body>

</body>
</html>
----

Within the `<body>`, add a template with a simple paragraph:

[source,html]
----
<template id="tws-counter-template">
  <p>Count:</p>
</template>
----

Below the template, implement a Custom Element that renders the template's contents:

[source,html]
----
<script>
  class Counter extends HTMLElement {
    constructor() {
      super();
      const template = document.getElementById("tws-counter-template");
      const content = template.content.cloneNode(true);
      this.append(content);
    }
  }
 customElements.define("tws-counter", Counter);
</script>
----

When you now add your Custom Element to the `<body>` (must be before above `<script>` tag), you should be able to see the text "Count:" rendered in your browser:

[source,html]
----
  <tws-counter></tws-counter>
----


== Add Button & Render Number

Now add an increment button to your component's template:

[source,html]
----
<button>increment</button>
----

Then start listening to its `click` event in the component:

[source,javascript]
----
class Counter extends HTMLElement {
  // ...
 connectedCallback() {
    const button = this.querySelector("button");
    button.addEventListener("click", this.increment.bind(this), true);
  }
 increment() {
    console.log("increment");
  }
}
----

Can you see the log output when clicking on the button?

Great, then you can add an element to the paragraph in your template, that we can afterwards select and use to display the current count:

[source,html]
----
<p>Count: <span class="count">0</span></p>"
----

The implementation of the remaining counter logic is up to you:

- Add a property on your component class to store the current count
- Initialize the property in the `constructor`
- Increment the property and update the `textContent` of the `<span>` with the incremented value

== Use Shadow DOM

Now that you have a working Custom Element you may refactor it to use Shadow DOM.

Attach a shadow root to your Custom Element in the `constructor`:

[source,javascript]
----
this.attachShadow({ mode: "open" });
----

Append the template contents to `this.shadowRoot` instead of the Custom Element itself. Adjust the rest of the component log to use the shadow root and make the component work as before.

Inspect the changes in your browser's dev tools.

== Style the Component

Add some "shadow styles" to the template:

[source,html]
----
<style>
  :host {
    display: flex;
    gap: 1rem;
    align-items: center;
  }
</style>
----

You may also try to add styles for the `button` element to the light DOM (e.g. in a `<style>` tag in the `<head>` of your document), to ensure they don't affect the component's button in the Shadow DOM.


== Futher Topics

Some ideas for further improvements of your component:

- Reflect the count to an HTML attribute of your Custom Element (i.e. allow to initialize/set the count or read the count via an attribute)
- https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent[Dispatch an event] with the new value whenever the count is incremented
- Add https://developers.google.com/web/fundamentals/web-components/shadowdom#stylehooks[style hooks], i.e. allow to customize the look of your Custom Element (e.g. the button's background color) via CSS Custom Properties
- Convert your Custom Element to a Lit component (you can use the https://lit.dev/playground/[Lit playground] for the sake of simplicity) – but you may want to go through the https://lit.dev/tutorial/[Lit tutorial] first
